### ISSUE TITLE
Customizable and Independent Inventory GUI Scale

### ISSUE THREAD

**Issue by MicrocontrollersDev** [IMB11-Mods/Flow#19]
Sorry if this is considered out of scope for this project. I play Minecraft at a GUI scale of normal as I prefer how my HUD looks. My only issue is the size of the inventory, which I think is much too small at this GUI scale. It would be nice if the inventory GUI scale could be customized independently of the normal GUI scale.

Such a mod [exists for 1.8.9](https://github.com/Moulberry/BetterScaledGUI). This mod only affects how the inventory GUI is rendered, everything else that would normally be affected by a change in GUI scale is untouched from the one set in video settings.

**Comment by IMB11** [comment]
This seems to be a little out of scope for Flow, maybe ask in the Fabric discord?
