### ISSUE TITLE
Issue with server startup

### ISSUE THREAD

**Issue by Cheesy-Brik** [IMB11-Mods/Flow#23]
Emi and flow seem to conflict when starting a server.jar causing this error
[latest.log](https://github.com/IMB11/Flow/files/15140488/latest.log)
This ofc isn't a major issue but it would be more convenient if it didn't do this

**Comment by IMB11** [comment]
Flow is a client side mod?? It's not meant for servers. Please read the modrinth page before installing mods.

**Comment by Poopooracoocoo** [comment]
Could probs fix https://github.com/IMB11/Flow/blob/main/src/main/resources/fabric.mod.json#L16
