### ISSUE TITLE
Incompatibility with Irons Spellbooks (Sinytra)

### ISSUE THREAD

**Issue by AvrgDerk** [IMB11-Mods/Flow#29]
Figure there won't be support for this as using this fabric mod with forge is already very experimental on its own but just wanted to report Flow losing all inventory transitions when Irons Spellbooks mod is installed.

1.20.1 Latest versions of both mods.

**Comment by IMB11** [comment]
You are using Sinyatra at your own risk, I cannot fix any issues you may encounter.
