### ISSUE TITLE
[Suggestion] Quilt support

### ISSUE THREAD

**Issue by MrGreenTea** [IMB11-Mods/Flow#3]
Hi, I really like the mod. 
I was testing around if I can run my server/modpack on Quilt to add some Quilt-only mods and had to disable your lovely mod because 

Quilt kept complaining that it needs fabricloader.

I would be very grateful if you would support `Quilt` as well if it is not to much of a hassle :)

**Comment by mineblock11** [comment]
Hi, I dont generally support Quilt Loader because it's more hassle for me than it has to be. An alternative would be to use Fabric Loader and find alternatives to the Quilt-Only mods.
