### ISSUE TITLE
Functionality confliction with REI **NOT-A-CRASH** -_-

### ISSUE THREAD

**Issue by Ynaught** [IMB11-Mods/Flow#30]
The REI menu just won't show up when opening the player inventory.

**Comment by EngurRuzgar** [comment]
Can you please send your game log? You can upload them to mclo.gs

**Comment by Ynaught** [comment]
Um. . . I'm not sure what a log would tell you? It's not like the game crashes or anything. The menu for REI just doesn't appear when you open your inventory. Idk if it's the same with JEI as well. I assume you just want me to re-enable the Flow mod, load into a world, open my inventory, close my inventory, then quit out of the game, yes? That's the log data you'd need?

I have no idea what mclo is so I'ma just send the log in a reply.

**Comment by Ynaught** [comment]
Is this what you were looking for?

Latest Log:
https://mclo.gs/7majbya

rei.log:
https://mclo.gs/tlOF9Yb

rei-issues.log:
https://mclo.gs/hYW41ZX

**Comment by IMB11** [comment]
No relevant logs, and this probably isn't related to Flow due to the amount of mods you have installed. Make sure you send the correct crash report/latest.log when the crash happens again.

I would recommend using EMI over JEI though, Flow works much better with EMI.

**Comment by Ynaught** [comment]
Did you actually do what I suggested by testing the 2 mods on your end before assuming it's my mod list? I only have 3 mods that effect hud. Yours, this one, and inmove. That's it. Please be through before jumping to conclusions. It's not a good look otherwise. And it is very impropper.

**Comment by IMB11** [comment]
It doesn't matter if it crashes? I still need logs to see any debug messages. I can't continue without logs, regardless of if I can easily reproduce the issue on my system, I need to see all debug messages.

**Comment by Ynaught** [comment]
But it's still important for documentation to identify if the problem is actually "my mods" or just function incompatibility between the two mods.

**Comment by IMB11** [comment]
Do you actually know what you're talking about? I need the logs, regardless of what your opinion is.

I've been developing mods for over 3 years now, I know how reproducibility works.

**Comment by IMB11** [comment]
This is going nowhere, I will create a incompatibilities issue megathread tommorow.
