### ISSUE TITLE
Incompatible with Advancement Plaques (I think)

### ISSUE THREAD

**Issue by Sternens0hn** [IMB11-Mods/Flow#31]
[crash-2024-07-01_00.40.50-client.txt](https://github.com/user-attachments/files/16046432/crash-2024-07-01_00.40.50-client.txt)

uh yeah, don't quote me on that tho

**Comment by EngurRuzgar** [comment]
![image](https://github.com/IMB11/Flow/assets/49247727/ea7744a1-1d68-4f5e-b028-a4ec5d8cabb5)
