### ISSUE TITLE
Flow doesn't respect your settings and resets them everytime you start MC

### ISSUE THREAD

**Issue by NattoRiisa** [IMB11-Mods/Flow#8]
just change any settings, save it, close and reopen.

**Comment by mineblock11** [comment]
Can you provide logs? This seems like a file system issue

**Comment by mrshmllow** [comment]
I was just about to mod this in myself lol. Thank you!!!

**Comment by NattoRiisa** [comment]
[latest.log](https://github.com/mineblock11/Flow/files/13294474/latest.log)
[current ATLauncher log uploaded up till game quitting]https://paste.atlauncher.com/view/68dc099d-4d44-4374-bbf1-8056ad4dd28c

**Comment by mineblock11** [comment]
> Quilt Loader

I cannot guarantee that my mods will work with the Quilt Loader. If you are using the Quilt Loader, please do not report any bugs to me. I will not be able to help you.
